// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJy_1g_I6uqI2DQu_J0cy8eOCU3y9t-A',
    appId: '1:782901453971:web:93ca46a60f7e54f1071966',
    messagingSenderId: '782901453971',
    projectId: 'flutter-login-auth-page',
    authDomain: 'flutter-login-auth-page.firebaseapp.com',
    storageBucket: 'flutter-login-auth-page.firebasestorage.app',
    measurementId: 'G-FHWPE6X72R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDH_Y1ueYYpMhRpc5DF0BAH1u_BaWTkWs',
    appId: '1:782901453971:android:f2ba82ffc68e3727071966',
    messagingSenderId: '782901453971',
    projectId: 'flutter-login-auth-page',
    storageBucket: 'flutter-login-auth-page.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz8lcaA0NWbspbjL2_B8748Qc4cnEL6VM',
    appId: '1:782901453971:ios:5ae7454b30de47e7071966',
    messagingSenderId: '782901453971',
    projectId: 'flutter-login-auth-page',
    storageBucket: 'flutter-login-auth-page.firebasestorage.app',
    iosBundleId: 'com.example.loginAuthForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz8lcaA0NWbspbjL2_B8748Qc4cnEL6VM',
    appId: '1:782901453971:ios:5ae7454b30de47e7071966',
    messagingSenderId: '782901453971',
    projectId: 'flutter-login-auth-page',
    storageBucket: 'flutter-login-auth-page.firebasestorage.app',
    iosBundleId: 'com.example.loginAuthForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvJy_1g_I6uqI2DQu_J0cy8eOCU3y9t-A',
    appId: '1:782901453971:web:1854bcb713644a35071966',
    messagingSenderId: '782901453971',
    projectId: 'flutter-login-auth-page',
    authDomain: 'flutter-login-auth-page.firebaseapp.com',
    storageBucket: 'flutter-login-auth-page.firebasestorage.app',
    measurementId: 'G-Z76D6FXVRR',
  );
}
